### ISSUE TITLE
Error on V14

### ISSUE THREAD

**Issue by f-9t9it** [flexcomng/erpnext_quick_install#16]
Thank you for the amazing script to easy install.

I tried it for v14 and it errors out when doing bench restart.
```
bench restart
$ supervisorctl restart frappe-bench-web:
frappe-bench-web:frappe-bench-frappe-web: stopped
frappe-bench-web:frappe-bench-node-socketio: stopped
frappe-bench-web:frappe-bench-frappe-web: ERROR (spawn error)
frappe-bench-web:frappe-bench-node-socketio: started
ERROR: supervisorctl restart frappe-bench-web:
subprocess.CalledProcessError: Command 'supervisorctl restart frappe-bench-web:' returned non-zero exit status 7.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/frappev14/.local/bin/bench", line 8, in <module>
    sys.exit(cli())
  File "/home/frappev14/.local/lib/python3.10/site-packages/bench/cli.py", line 132, in cli
    bench_command()
  File "/home/frappev14/.local/lib/python3.10/site-packages/bench/commands/utils.py", line 41, in restart
    Bench(".").reload(web, supervisor, systemd)
  File "/home/frappev14/.local/lib/python3.10/site-packages/bench/utils/render.py", line 126, in wrapper_fn
    return fn(*args, **kwargs)
  File "/home/frappev14/.local/lib/python3.10/site-packages/bench/bench.py", line 152, in reload
    restart_supervisor_processes(bench_path=self.name, web_workers=web, _raise=_raise)
  File "/home/frappev14/.local/lib/python3.10/site-packages/bench/utils/bench.py", line 342, in restart_supervisor_processes
    failure = bench.run(f"{sudo}supervisorctl restart {group}", _raise=_raise)
  File "/home/frappev14/.local/lib/python3.10/site-packages/bench/bench.py", line 48, in run
    return exec_cmd(cmd, cwd=cwd or self.cwd, _raise=_raise)
  File "/home/frappev14/.local/lib/python3.10/site-packages/bench/utils/__init__.py", line 169, in exec_cmd
    raise CommandFailedError(cmd) from subprocess.CalledProcessError(return_code, cmd)
bench.exceptions.CommandFailedError: supervisorctl restart frappe-bench-web:
```

This does not get resolved even when I do almost everything mentioned on forum.

```
23  git clone https://github.com/flexcomng/erpnext_quick_install.git
   24  cd erpnext_quick_install/
   25  sudo chmod +x erpnext_install.sh
   26  source erpnext_install.sh
   27  bench setup socketio
   28  bench setup supervisor
   29  bench setup redis
   30  sudo supervisorctl reload
   31  bench restart
   32  sudo bench restart
   33  sudo reboot now
   34  cd frappe-bench/
   35  sudo service supervisor stop
   36  sudo service supervisor start
   37  bench restart
   38  bench start
   39  sudo ln -s `pwd`/config/supervisor.conf /etc/supervisor/conf.d/frappe-bench.conf
   40  bench setup supervisor
   41  sudo vim /etc/supervisor/supervisord.conf
   42  sudo bench setup production frappev14
   43  sudo supervisorctl restart all
   44  bench restart
   45  python --version
   46  python -V
   47  python --V
   48  python
   49  python3
   50  ls -la env/bin/python3
   51  sudo apt purge python3.12
   52  killall -9 node
   53  supervisorctl restart all
   54  bench restart
   55  bench doctor
   56  bench update --requirements
   57  bench setup redis
   58  bench setup socketio
   59  bench retry-upgrade
   60  sudo service nginx restart
   61  sudo supervisorctl reload
   62  bench restart
   63  sudo bench setup production frappev14
   64  bench restart
   65  bench setup socketio
   66  bench setup supervisor
   67  bench setup redis
   68  sudo supervisorctl reload
   69  sudo systemctl enable socketio --now
   70  sudo systemctl enable sockeio --now
   71  sudo systemctl start socketio --now
   72  sudo systemctl status *
   73  sudo systemctl status supervisor 
   74  sudo systemctl start supervisor  --now
   75  sudo systemctl restart supervisor  --now
   76  bench restart
   77  sudo supervisorctl restart all
   78  sudo systemctl status redis
   79  sudo systemctl restart redis --now
   80  sudo systemctl restart socketio --now
   81  sudo systemctl restart supervisorctl --now
   82  sudo systemctl restart supervisor --now
   83  bench restart --web --supervisor
   84  sudo nano /etc/supervisor/supervisord.conf
   85  bench setup supervisor
   86  sudo ln -s `pwd`/config/supervisor.conf /etc/supervisor/conf.d/frappe-bench.conf
   87  sudo rm -rf /etc/supervisor/conf.d/frappe-bench.conf 
   88  sudo ln -s `pwd`/config/supervisor.conf /etc/supervisor/conf.d/frappe-bench.conf
   89  sudo service supervisorctl reload
   90  sudo service supervisor reload
   91  bench restart
```

Whole command list history attached above.  I will try to search more and if I find a solution then I will share it here and on forum. 

UDPATE: Found the issue. It was cpu instruction causing core dump. 

`19:50:14 web.1         | Illegal instruction (core dumped)`

**Comment by f-9t9it** [comment]
Yes i reported already that its the cpu issue over proxmox when avx/avx2 is not active. 

Also posted in forum.
Will close this issue but will make pr to update readme to add this as documentation for such issue.
