### ISSUE TITLE
OSError: b'./apps.txt' Not Found

### ISSUE THREAD

**Issue by scott-mackenzie** [flexcomng/erpnext_quick_install#33]
**Script not working.  Any ideas?**

`Enter the Administrator password:
Confirm password:
Password confirmed

Now setting up your site. This might take a few minutes. Please wait...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/frappeuser/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 114, in <module>
    main()
  File "/opt/frappeuser/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    commands = get_app_groups()
               ^^^^^^^^^^^^^^^^
  File "/opt/frappeuser/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 27, in get_app_groups
    for app in get_apps():
               ^^^^^^^^^^
  File "/opt/frappeuser/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 107, in get_apps
    return frappe.get_all_apps(with_internal_apps=False, sites_path=".")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/frappeuser/frappe-bench/apps/frappe/frappe/__init__.py", line 1555, in get_all_apps
    apps = get_file_items(os.path.join(sites_path, "apps.txt"), raise_not_found=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/frappeuser/frappe-bench/apps/frappe/frappe/__init__.py", line 1724, in get_file_items
    content = read_file(path, raise_not_found=raise_not_found)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/frappeuser/frappe-bench/apps/frappe/frappe/__init__.py", line 1752, in read_file
    raise OSError(f"{path} Not Found")
OSError: b'./apps.txt' Not Found
An error occurred on line 369 with exit status 0`

**Comment by flexcomng** [comment]
This may have been the result of a failed frappe pull. i have seen this issue occur even with manual install where a slight network interruption breaks frappe install.
